spring.application.name=spring-rpg
server.port=${PORT:8080}
spring.datasource.url=${DATABASE_URL}
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
